import { create } from 'zustand';
import { persist } from 'zustand/middleware';

export type Language = 'fr' | 'en' | 'sw';

export const translations = {
  fr: {
    brandName: 'ZANDO YETU',
    brandTagline: "Plateforme Mode & Marketplace de Lubumbashi",
    searchPlaceholder: 'Rechercher vêtements, chaussures, accessoires...',
    categories: 'Catégories',
    flashSales: 'Ventes Flash',
    endingIn: 'Se termine dans',
    featuredStores: 'Boutiques Partenaires',
    allProducts: 'Tous les Articles',
    trendingNow: 'Tendances du Moment',
    addToCart: 'Ajouter au Panier',
    addedToCart: 'Ajouté au panier !',
    buyNow: 'Acheter Maintenant',
    viewDetails: 'Voir Détails',
    outOfStock: 'Rupture de Stock',
    onlyLeft: 'Plus que {x} en stock !',
    freeShippingBanner: "Livraison Gratuite \u00e0 Lubumbashi d\u00e8s $50 d\u2019achats",
    cartTitle: 'Mon Panier',
    cartEmpty: 'Votre panier est vide',
    cartEmptySubtitle: 'Découvrez nos collections exclusives et remplissez votre garde-robe.',
    subtotal: 'Sous-total',
    deliveryFee: 'Frais de Livraison',
    freeDelivery: 'Gratuit',
    promoDiscount: 'Remise Code Promo',
    pointsDiscount: 'Remise Points Fidélité',
    total: 'Total à Payer',
    proceedToCheckout: 'Passer à la Caisse',
    promoCodePlaceholder: 'Entrez un code promo',
    applyPromo: 'Appliquer',
    promoApplied: 'Code promo appliqué avec succès !',
    redeemPoints: 'Utiliser mes Points Fidélité',
    pointsAvailable: 'Points disponibles',
    pointsDiscountValue: '1 point = 0.20 USD de remise immédiate',
    deliveryMethod: 'Mode de Livraison',
    cashOnDelivery: 'Paiement Cash à la Livraison',
    inStorePickup: 'Retrait Gratuit en Boutique',
    deliveryAddress: 'Adresse de Livraison à Lubumbashi',
    selectCommune: 'Sélectionner la Commune',
    selectLandmark: 'Point de Repère le plus proche',
    addressDetails: 'Avenue, N°, Détails de la maison',
    mapsLink: 'Lien Google Maps (Optionnel)',
    completeOrder: 'Confirmer la Commande',
    orderSuccessTitle: 'Commande Confirmée !',
    orderSuccessMessage: 'Votre commande a été transmise aux vendeurs. Vous recevrez une confirmation.',
    trackOrders: 'Suivre mes Commandes',
    continueShopping: 'Continuer mes Achats',
    loginTitle: 'Connexion à votre Compte',
    registerTitle: 'Créer un Compte',
    email: 'Adresse E-mail',
    password: 'Mot de Passe',
    fullName: 'Nom Complet',
    genderPreference: 'Préférence de Mode',
    genderWomen: 'Femmes',
    genderMen: 'Hommes',
    genderAll: 'Toutes les Collections',
    alreadyHaveAccount: 'Déjà un compte ? Connectez-vous',
    needAccount: "Vous n'avez pas de compte ? Inscrivez-vous",
    myAccount: 'Mon Profil',
    myOrders: 'Historique des Commandes',
    signOut: 'Déconnexion',
    reviews: 'Avis Clients',
    writeReview: 'Laisser un Avis',
    verifiedPurchase: 'Achat Vérifié',
    storeFollowers: 'abonnés',
    followStore: 'Suivre la Boutique',
    unfollowStore: 'Abonné',
    guaranteesTitle: 'Nos Engagements',
    guaranteeDelivery: 'Livraison Rapide à Lubumbashi',
    guaranteePayment: 'Paiement Sécurisé à la Réception',
    guaranteeReturns: 'Retours Faciles & Échanges Garantis',

    // Account Deletion
    deleteAccount: 'Supprimer mon Compte',
    deleteAccountWarning: 'Cette action est irréversible. Toutes vos données, commandes et points de fidélité seront définitivement supprimés. Tapez "{confirmWord}" pour confirmer.',
    deleteAccountConfirmWord: 'SUPPRIMER',
    deleteAccountConfirmPlaceholder: 'Tapez SUPPRIMER pour confirmer',
    deleteAccountSuccess: 'Votre compte a été supprimé avec succès.',
    deleteAccountProcessing: 'Suppression en cours...',
    deleteAccountCancel: 'Annuler',

    // Profile Page
    profileTitle: 'Mon Profil Client',
    profileSubtitle: 'Gérez vos coordonnées et préférences de livraison.',
    profileLoginPrompt: 'Connectez-vous pour gérer vos informations personnelles.',
    profileLoginButton: 'Se Connecter',
    loyaltyPointsTitle: 'Solde Points Fidélité',
    loyaltyPointsSubtitle: 'Valable sur vos prochains achats Zando Yetu',
    loyaltyPointsEquiv: '≈ {value} USD',
    emailLabel: 'Adresse E-mail',
    phoneLabel: 'Numéro de Téléphone (WhatsApp / Appel)',
    phonePlaceholder: 'Ex: +243 970 000 000',
    defaultAddressLabel: 'Adresse de Livraison par Défaut (Lubumbashi)',
    defaultAddressPlaceholder: 'Commune, Quartier, Avenue, Numéro...',
    saveButton: 'Sauvegarder',
    saving: 'Enregistrement...',
    saveSuccess: 'Informations enregistrées avec succès.',

    // Address Form
    addressFormTitle: 'Adresse de Livraison à Lubumbashi',
    communeLabel: 'Commune',
    communePlaceholder: 'Sélectionner votre commune',
    landmarkLabel: 'Point de Repère Proche',
    landmarkPlaceholder: 'Sélectionner un repère',
    landmarkInputPlaceholder: 'Ex: Arrêt Horizon, Rond-point Carrefour',
    streetLabel: 'Avenue, Numéro, Détails Précis de la maison',
    streetPlaceholder: 'Ex: Avenue Kapenda N°42, Porte métallique noire',
    mapsLinkLabel: 'Lien Google Maps (Optionnel)',
    mapsLinkPlaceholder: 'Collez le lien de partage Google Maps...',

    // Order Tracking
    stepValidation: 'Validation',
    stepPreparation: 'Préparation',
    stepDelivery: 'En Livraison',
    stepDelivered: 'Livré',
    orderCancelled: 'Cette commande a été annulée.',

    // Orders Page
    ordersTitle: 'Historique des Commandes',
    ordersSubtitle: "Suivez l'état d'avancement de vos achats en temps réel.",
    ordersLoginPrompt: 'Connectez-vous pour consulter l\'historique et le suivi de vos commandes.',
    ordersEmpty: 'Aucune commande pour le moment',
    ordersEmptySubtitle: 'Vos articles achetés apparaîtront ici avec leur suivi.',
    ordersExplore: 'Explorer les collections',
    ordersLoading: 'Chargement de vos commandes...',
    orderNumber: 'Commande',
    orderTotal: 'Total',
    orderQuantity: 'Quantité',
    orderViewItem: "Voir l'article",
    orderCreatedIds: 'Numéros de commande créés :',

    // Checkout Page
    checkoutTitle: 'Validation & Paiement de Commande',
    backToCart: 'Retour au panier',
    cashOnDeliveryDesc: 'Livraison à domicile à Lubumbashi',
    inStorePickupDesc: 'Retrait direct chez le vendeur (Gratuit)',
    loginToCheckout: 'Vous devez être connecté pour finaliser votre commande.',
    loginToCheckoutLink: 'Cliquez ici pour vous connecter',
    orderSummaryTitle: 'Total de la Commande',
    processing: 'Traitement en cours...',
    secureTransaction: '🔒 Transaction sécurisée et vérifiée par Zando Yetu.',
    addressRequired: 'Veuillez renseigner tous les champs obligatoires de votre adresse de livraison.',
    checkoutError: 'Une erreur est survenue lors du paiement.',
    backToShop: 'Retour à la boutique',

    // Cart Page
    clearCart: 'Vider le panier',
    removeItem: 'Supprimer',
    orderSummary: 'Récapitulatif de Commande',
    freeDeliveryThreshold: 'Gratuit (Dès $50)',
    viewFullCart: 'Voir Panier Complet',

    // Cart Drawer Item Labels
    sizeLabel: 'Taille',
    colorLabel: 'Couleur',

    // Promo Code
    promoCodeTitle: 'Code Promotionnel',
    promoCodeActive: 'Code {code} (-{percent}%) actif',
    promoCodeInvalid: 'Code promo invalide ou expiré.',
    promoCodeEmpty: 'Veuillez saisir un code.',
    promoCodeExample: 'Ex: ZANDO10',

    // Fidelity Points
    fidelityTitle: 'Points de Fidélité',
    fidelityAvailable: '{count} points disponibles',
    fidelityRate: '1 point = $0.20 USD de remise déduite directement sur votre commande.',
    fidelityDiscount: 'Remise accordée : -{amount}',

    // Mobile Nav
    navHome: 'Accueil',
    navOrders: 'Commandes',
    navCart: 'Panier',
    navProfile: 'Profil',

    // Footer
    footerDescription: 'La première place de marché dédiée à la mode et aux créateurs à Lubumbashi. Connectez-vous aux meilleures boutiques locales.',
    footerCommunesTitle: 'Communes Desservies',
    footerCommunesList1: 'Lubumbashi Centre & Golf',
    footerCommunesList2: 'Kampemba & Bel-Air',
    footerCommunesList3: 'Annexe & Joli Site',
    footerCommunesList4: 'Katuba & Kenya',
    footerCommunesList5: 'Kamalondo & Ruashi',
    footerCustomerServiceTitle: 'Service Client',
    footerOrderTracking: 'Suivi de commande',
    footerMyCart: 'Mon Panier',
    footerMyAccount: 'Mon Compte',
    footerLoginRegister: 'Connexion / Inscription',
    footerPaymentTitle: 'Paiements & Devises',
    footerPaymentDesc: 'Nous acceptons les paiements en Francs Congolais (CDF) et en Dollars Américains (USD) à la livraison ou en boutique.',
    footerCopyright: '© {year} Zando Yetu. Tous droits réservés. Lubumbashi, République Démocratique du Congo.',
    footerGuaranteeDeliveryDesc: 'Lubumbashi, Haut-Katanga (RDC)',
    footerGuaranteePaymentDesc: 'Cash à la livraison & Mobile Money',
    footerGuaranteeReturnsDesc: 'Vérification sur place à la réception',

    // Login / Connection
    loginButton: 'Connexion',
    loginRegisterMobile: 'Connexion / Inscription',

    // WhatsApp Inquiries
    whatsappInquiry: 'Discuter sur WhatsApp',
    whatsappStoreInquiry: 'Contacter la boutique sur WhatsApp',
    whatsappProductMsg: 'Bonjour, je suis intéressé par l\'article "{title}" ({price}) sur Zando Yetu : {link}',
    whatsappStoreMsg: 'Bonjour, je vous contacte depuis votre boutique {name} sur Zando Yetu.',

    // Product & Variants
    scarcityWarning: '🔥 Plus que {count} disponible(s) !',
    selectSize: 'Taille sélectionnée',
    selectColor: 'Couleur sélectionnée',
    viewCatalog: 'Retour au catalogue',
    productNotFound: 'Article introuvable',
    productNotFoundDesc: "Cet article n'est plus disponible ou a été retiré.",
    storeNotFound: 'Boutique introuvable',
    storeNotFoundDesc: "Cette boutique n'est plus active sur Zando Yetu.",
    itemsForSale: 'Articles en vente ({count})',
    noItemsInStore: 'Aucun article en stock actuellement',
    noItemsInStoreDesc: 'Revenez bientôt pour découvrir de nouveaux arrivages.',
    stockRemaining: '{count} en stock',
    colorAvailable: '{color}',

    // Reviews
    reviewTitle: 'Avis & Évaluations Clients',
    leaveReview: 'Laisser un avis sur cet article',
    reviewPlaceholder: 'Partagez votre avis sur la qualité, la coupe ou la livraison...',
    submitReview: 'Publier mon avis',
    submittingReview: 'Publication...',
    noReviews: 'Aucun avis pour le moment. Soyez le premier à donner votre avis !',
    mustLoginToReview: 'Connectez-vous pour laisser un avis sur cet article.',
    verifiedCustomer: 'Achat Vérifié',
    wishlistAdded: 'Ajouté aux favoris',
    wishlistRemoved: 'Retiré des favoris',

    // Mega Menu & Storefront V2
    allRayons: 'Tous les Rayons',
    megaMenuWomen: 'Femmes',
    megaMenuMen: 'Hommes',
    megaMenuKids: 'Enfants',
    megaMenuDresses: 'Robes & Ensembles',
    megaMenuShoes: 'Chaussures',
    megaMenuBags: 'Sacs & Accessoires',
    megaMenuDesigners: 'Créateurs Katangais',
    dealsTitle: 'Nos Bonnes Affaires',
    dealsSubtitle: 'Sélection exclusive à prix réduits pour Lubumbashi',
    trendsTitle: 'Tendances du Moment',
    officialStoresTitle: 'Boutiques Officielles',
    expressDeliveryTag: 'Livraison 24h-48h à Lubumbashi',
    newArrivals: 'Nouveautés',
    bestSellers: 'Meilleures Ventes',
    under20: 'Moins de $20',
    guestBannerText: 'Rejoignez Zando Yetu pour cumuler des points fidélité et suivre vos commandes en direct !',
    guestBannerBtn: 'Créer un compte',
    wishlistTitle: 'Mes Favoris',
    featuredBrandHighlight: 'Sélection Spéciale Lubumbashi',
    flashSaleEndsSoon: 'Offre limitée dans le temps',
    viewAllDeals: 'Voir toutes les offres',
  },
  en: {
    brandName: 'ZANDO YETU',
    brandTagline: "Lubumbashi's Premier Fashion Marketplace",
    searchPlaceholder: 'Search clothing, shoes, accessories...',
    categories: 'Categories',
    flashSales: 'Flash Sales',
    endingIn: 'Ends in',
    featuredStores: 'Featured Stores',
    allProducts: 'All Products',
    trendingNow: 'Trending Now',
    addToCart: 'Add to Cart',
    addedToCart: 'Added to cart!',
    buyNow: 'Buy Now',
    viewDetails: 'View Details',
    outOfStock: 'Out of Stock',
    onlyLeft: 'Only {x} left in stock!',
    freeShippingBanner: 'Free Delivery in Lubumbashi on orders over $50',
    cartTitle: 'Shopping Cart',
    cartEmpty: 'Your cart is empty',
    cartEmptySubtitle: 'Explore our curated collections and elevate your style.',
    subtotal: 'Subtotal',
    deliveryFee: 'Delivery Fee',
    freeDelivery: 'Free',
    promoDiscount: 'Promo Code Discount',
    pointsDiscount: 'Loyalty Points Discount',
    total: 'Total Due',
    proceedToCheckout: 'Proceed to Checkout',
    promoCodePlaceholder: 'Enter promo code',
    applyPromo: 'Apply',
    promoApplied: 'Promo code applied successfully!',
    redeemPoints: 'Redeem Loyalty Points',
    pointsAvailable: 'Available points',
    pointsDiscountValue: '1 point = $0.20 USD instant discount',
    deliveryMethod: 'Delivery Method',
    cashOnDelivery: 'Cash on Delivery',
    inStorePickup: 'Free In-Store Pickup',
    deliveryAddress: 'Lubumbashi Delivery Address',
    selectCommune: 'Select Commune',
    selectLandmark: 'Closest Landmark',
    addressDetails: 'Street, House No., Apartment details',
    mapsLink: 'Google Maps Link (Optional)',
    completeOrder: 'Place Order',
    orderSuccessTitle: 'Order Confirmed!',
    orderSuccessMessage: 'Your order has been forwarded to the vendors. You will receive real-time updates.',
    trackOrders: 'Track Orders',
    continueShopping: 'Continue Shopping',
    loginTitle: 'Sign In to Your Account',
    registerTitle: 'Create an Account',
    email: 'Email Address',
    password: 'Password',
    fullName: 'Full Name',
    genderPreference: 'Shopping Preference',
    genderWomen: 'Women',
    genderMen: 'Men',
    genderAll: 'All Fashion',
    alreadyHaveAccount: 'Already have an account? Sign in',
    needAccount: "Don't have an account? Sign up",
    myAccount: 'My Profile',
    myOrders: 'My Orders',
    signOut: 'Sign Out',
    reviews: 'Customer Reviews',
    writeReview: 'Write a Review',
    verifiedPurchase: 'Verified Purchase',
    storeFollowers: 'followers',
    followStore: 'Follow Store',
    unfollowStore: 'Following',
    guaranteesTitle: 'Our Guarantees',
    guaranteeDelivery: 'Express Delivery in Lubumbashi',
    guaranteePayment: 'Secure Payment on Delivery',
    guaranteeReturns: 'Hassle-free Returns & Exchanges',

    // Account Deletion
    deleteAccount: 'Delete My Account',
    deleteAccountWarning: 'This action is irreversible. All your data, orders, and loyalty points will be permanently deleted. Type "{confirmWord}" to confirm.',
    deleteAccountConfirmWord: 'DELETE',
    deleteAccountConfirmPlaceholder: 'Type DELETE to confirm',
    deleteAccountSuccess: 'Your account has been successfully deleted.',
    deleteAccountProcessing: 'Deleting account...',
    deleteAccountCancel: 'Cancel',

    // Profile Page
    profileTitle: 'My Customer Profile',
    profileSubtitle: 'Manage your contact details and delivery preferences.',
    profileLoginPrompt: 'Sign in to manage your personal information.',
    profileLoginButton: 'Sign In',
    loyaltyPointsTitle: 'Loyalty Points Balance',
    loyaltyPointsSubtitle: 'Redeemable on your next Zando Yetu purchases',
    loyaltyPointsEquiv: '≈ {value} USD',
    emailLabel: 'Email Address',
    phoneLabel: 'Phone Number (WhatsApp / Call)',
    phonePlaceholder: 'E.g.: +243 970 000 000',
    defaultAddressLabel: 'Default Delivery Address (Lubumbashi)',
    defaultAddressPlaceholder: 'Commune, Neighbourhood, Street, Number...',
    saveButton: 'Save',
    saving: 'Saving...',
    saveSuccess: 'Information saved successfully.',

    // Address Form
    addressFormTitle: 'Lubumbashi Delivery Address',
    communeLabel: 'Commune',
    communePlaceholder: 'Select your commune',
    landmarkLabel: 'Nearest Landmark',
    landmarkPlaceholder: 'Select a landmark',
    landmarkInputPlaceholder: 'E.g.: Horizon Stop, Carrefour Roundabout',
    streetLabel: 'Street, Number, Precise House Details',
    streetPlaceholder: 'E.g.: Avenue Kapenda No.42, Black metal gate',
    mapsLinkLabel: 'Google Maps Link (Optional)',
    mapsLinkPlaceholder: 'Paste your Google Maps share link...',

    // Order Tracking
    stepValidation: 'Validation',
    stepPreparation: 'Preparation',
    stepDelivery: 'In Delivery',
    stepDelivered: 'Delivered',
    orderCancelled: 'This order has been cancelled.',

    // Orders Page
    ordersTitle: 'Order History',
    ordersSubtitle: 'Track the progress of your purchases in real-time.',
    ordersLoginPrompt: 'Sign in to view your order history and tracking.',
    ordersEmpty: 'No orders yet',
    ordersEmptySubtitle: 'Your purchased items will appear here with tracking.',
    ordersExplore: 'Explore collections',
    ordersLoading: 'Loading your orders...',
    orderNumber: 'Order',
    orderTotal: 'Total',
    orderQuantity: 'Quantity',
    orderViewItem: 'View item',
    orderCreatedIds: 'Created order numbers:',

    // Checkout Page
    checkoutTitle: 'Order Validation & Payment',
    backToCart: 'Back to cart',
    cashOnDeliveryDesc: 'Home delivery in Lubumbashi',
    inStorePickupDesc: 'Pick up directly from the vendor (Free)',
    loginToCheckout: 'You must be logged in to complete your order.',
    loginToCheckoutLink: 'Click here to sign in',
    orderSummaryTitle: 'Order Total',
    processing: 'Processing...',
    secureTransaction: '🔒 Secure transaction verified by Zando Yetu.',
    addressRequired: 'Please fill in all required delivery address fields.',
    checkoutError: 'An error occurred during payment.',
    backToShop: 'Back to shop',

    // Cart Page
    clearCart: 'Clear cart',
    removeItem: 'Remove',
    orderSummary: 'Order Summary',
    freeDeliveryThreshold: 'Free (Over $50)',
    viewFullCart: 'View Full Cart',

    // Cart Drawer Item Labels
    sizeLabel: 'Size',
    colorLabel: 'Color',

    // Promo Code
    promoCodeTitle: 'Promo Code',
    promoCodeActive: 'Code {code} (-{percent}%) active',
    promoCodeInvalid: 'Invalid or expired promo code.',
    promoCodeEmpty: 'Please enter a code.',
    promoCodeExample: 'E.g.: ZANDO10',

    // Fidelity Points
    fidelityTitle: 'Loyalty Points',
    fidelityAvailable: '{count} points available',
    fidelityRate: '1 point = $0.20 USD discount applied directly to your order.',
    fidelityDiscount: 'Discount applied: -{amount}',

    // Mobile Nav
    navHome: 'Home',
    navOrders: 'Orders',
    navCart: 'Cart',
    navProfile: 'Profile',

    // Footer
    footerDescription: "Lubumbashi's first marketplace dedicated to fashion and local designers. Connect with the best local stores.",
    footerCommunesTitle: 'Delivery Areas',
    footerCommunesList1: 'Lubumbashi Centre & Golf',
    footerCommunesList2: 'Kampemba & Bel-Air',
    footerCommunesList3: 'Annexe & Joli Site',
    footerCommunesList4: 'Katuba & Kenya',
    footerCommunesList5: 'Kamalondo & Ruashi',
    footerCustomerServiceTitle: 'Customer Service',
    footerOrderTracking: 'Order Tracking',
    footerMyCart: 'My Cart',
    footerMyAccount: 'My Account',
    footerLoginRegister: 'Sign In / Register',
    footerPaymentTitle: 'Payments & Currencies',
    footerPaymentDesc: 'We accept payments in Congolese Francs (CDF) and US Dollars (USD) on delivery or in-store.',
    footerCopyright: '© {year} Zando Yetu. All rights reserved. Lubumbashi, Democratic Republic of Congo.',
    footerGuaranteeDeliveryDesc: 'Lubumbashi, Haut-Katanga (DRC)',
    footerGuaranteePaymentDesc: 'Cash on delivery & Mobile Money',
    footerGuaranteeReturnsDesc: 'On-the-spot verification upon receipt',

    // Login / Connection
    loginButton: 'Sign In',
    loginRegisterMobile: 'Sign In / Register',

    // WhatsApp Inquiries
    whatsappInquiry: 'Chat on WhatsApp',
    whatsappStoreInquiry: 'Contact Store on WhatsApp',
    whatsappProductMsg: 'Hello, I am interested in the item "{title}" ({price}) on Zando Yetu: {link}',
    whatsappStoreMsg: 'Hello, I am contacting you regarding your store {name} on Zando Yetu.',

    // Product & Variants
    scarcityWarning: '🔥 Only {count} left in stock!',
    selectSize: 'Selected Size',
    selectColor: 'Selected Color',
    viewCatalog: 'Back to catalog',
    productNotFound: 'Product not found',
    productNotFoundDesc: 'This item is no longer available or has been removed.',
    storeNotFound: 'Store not found',
    storeNotFoundDesc: 'This store is no longer active on Zando Yetu.',
    itemsForSale: 'Items for sale ({count})',
    noItemsInStore: 'No items in stock currently',
    noItemsInStoreDesc: 'Check back soon for new arrivals.',
    stockRemaining: '{count} in stock',
    colorAvailable: '{color}',

    // Reviews
    reviewTitle: 'Customer Reviews & Ratings',
    leaveReview: 'Write a review for this item',
    reviewPlaceholder: 'Share your review on quality, fit, or delivery...',
    submitReview: 'Submit Review',
    submittingReview: 'Submitting...',
    noReviews: 'No reviews yet. Be the first to leave a review!',
    mustLoginToReview: 'Sign in to leave a review for this item.',
    verifiedCustomer: 'Verified Purchase',
    wishlistAdded: 'Added to wishlist',
    wishlistRemoved: 'Removed from wishlist',

    // Mega Menu & Storefront V2
    allRayons: 'All Departments',
    megaMenuWomen: 'Women',
    megaMenuMen: 'Men',
    megaMenuKids: 'Kids',
    megaMenuDresses: 'Dresses & Sets',
    megaMenuShoes: 'Shoes',
    megaMenuBags: 'Bags & Accessories',
    megaMenuDesigners: 'Katanga Designers',
    dealsTitle: 'Our Best Deals',
    dealsSubtitle: 'Exclusive discounted selection for Lubumbashi',
    trendsTitle: 'Trending Now',
    officialStoresTitle: 'Official Stores',
    expressDeliveryTag: '24h-48h Delivery in Lubumbashi',
    newArrivals: 'New Arrivals',
    bestSellers: 'Best Sellers',
    under20: 'Under $20',
    guestBannerText: 'Join Zando Yetu to earn loyalty points and track your orders in real-time!',
    guestBannerBtn: 'Create Account',
    wishlistTitle: 'My Wishlist',
    featuredBrandHighlight: 'Lubumbashi Special Selection',
    flashSaleEndsSoon: 'Limited-time offer',
    viewAllDeals: 'View all deals',
  },
  sw: {
    brandName: 'ZANDO YETU',
    brandTagline: 'Soko Kuu ya Mitindo ya Lubumbashi',
    searchPlaceholder: 'Tafuta mavazi, viatu, vifaa...',
    categories: 'Makundi',
    flashSales: 'Mauzo ya Haraka',
    endingIn: 'Inamalizika ndani ya',
    featuredStores: 'Maduka Maarufu',
    allProducts: 'Bidhaa Zote',
    trendingNow: 'Zinazopendwa Zaidi',
    addToCart: 'Weka Kwenye Kikapu',
    addedToCart: 'Imewekwa kwenye kikapu!',
    buyNow: 'Nunua Sasa',
    viewDetails: 'Tazama Maelezo',
    outOfStock: 'Imeisha',
    onlyLeft: 'Zimebaki {x} tu!',
    freeShippingBanner: 'Usafirishaji Bila Malipo Lubumbashi kuanzia $50',
    cartTitle: 'Kikapu Changu',
    cartEmpty: 'Kikapu chako kiko tupu',
    cartEmptySubtitle: 'Tazama mikusanyiko yetu na ujaze kabati lako.',
    subtotal: 'Jumla Ndogo',
    deliveryFee: 'Ada ya Usafirishaji',
    freeDelivery: 'Bure',
    promoDiscount: 'Punguzo la Promo',
    pointsDiscount: 'Punguzo la Alama za Uaminifu',
    total: 'Jumla ya Kulipa',
    proceedToCheckout: 'Endelea Kulipa',
    promoCodePlaceholder: 'Ingiza msimbo wa punguzo',
    applyPromo: 'Tumia',
    promoApplied: 'Msimbo umetumiwa kikamilifu!',
    redeemPoints: 'Tumia Alama za Uaminifu',
    pointsAvailable: 'Alama zilizopo',
    pointsDiscountValue: 'Alama 1 = Punguzo la $0.20 USD papo hapo',
    deliveryMethod: 'Njia ya Uwasilishaji',
    cashOnDelivery: 'Malipo ya Pesa Wakati wa Kupokea',
    inStorePickup: 'Kuchukua Dukani Bure',
    deliveryAddress: 'Anwani ya Uwasilishaji Lubumbashi',
    selectCommune: 'Chagua Manispaa (Commune)',
    selectLandmark: 'Eneo la Karibu Zaidi',
    addressDetails: 'Mtaa, Nambari ya Nyumba',
    mapsLink: 'Kiungo cha Google Maps (Hiari)',
    completeOrder: 'Thibitisha Agizo',
    orderSuccessTitle: 'Agizo Limethibitishwa!',
    orderSuccessMessage: 'Agizo lako limetumwa kwa wauzaji. Utapokea taarifa ya uthibitisho.',
    trackOrders: 'Fuatilia Maagizo',
    continueShopping: 'Endelea Kununua',
    loginTitle: 'Ingia kwenye Akaunti',
    registerTitle: 'Fungua Akaunti Mpya',
    email: 'Barua Pepe',
    password: 'Nenosiri',
    fullName: 'Jina Kamili',
    genderPreference: 'Upendeleo wa Mitindo',
    genderWomen: 'Wanawake',
    genderMen: 'Wanaume',
    genderAll: 'Mikusanyiko Yote',
    alreadyHaveAccount: 'Je, una akaunti tayari? Ingia',
    needAccount: 'Huna akaunti? Jisajili sasa',
    myAccount: 'Wasifu Wangu',
    myOrders: 'Historia ya Maagizo',
    signOut: 'Toka',
    reviews: 'Maoni ya Wateja',
    writeReview: 'Andika Maoni',
    verifiedPurchase: 'Ununuzi Uliothibitishwa',
    storeFollowers: 'wafuasi',
    followStore: 'Fuata Duka',
    unfollowStore: 'Unafuata',
    guaranteesTitle: 'Ahadi Zetu',
    guaranteeDelivery: 'Uwasilishaji wa Haraka Lubumbashi',
    guaranteePayment: 'Malipo Salama Wakati wa Kupokea',
    guaranteeReturns: 'Kurudisha Bidhaa na Kubadilisha Rahisi',

    // Account Deletion
    deleteAccount: 'Futa Akaunti Yangu',
    deleteAccountWarning: 'Kitendo hiki hakiwezi kurudishwa. Data yako yote, maagizo na alama za uaminifu zitafutwa kabisa. Andika "{confirmWord}" kuthibitisha.',
    deleteAccountConfirmWord: 'FUTA',
    deleteAccountConfirmPlaceholder: 'Andika FUTA kuthibitisha',
    deleteAccountSuccess: 'Akaunti yako imefutwa kikamilifu.',
    deleteAccountProcessing: 'Inafuta akaunti...',
    deleteAccountCancel: 'Ghairi',

    // Profile Page
    profileTitle: 'Wasifu Wangu wa Mteja',
    profileSubtitle: 'Simamia maelezo yako ya mawasiliano na upendeleo wa uwasilishaji.',
    profileLoginPrompt: 'Ingia ili kudhibiti taarifa zako binafsi.',
    profileLoginButton: 'Ingia',
    loyaltyPointsTitle: 'Salio la Alama za Uaminifu',
    loyaltyPointsSubtitle: 'Zinatumika kwa ununuzi wako ujao wa Zando Yetu',
    loyaltyPointsEquiv: '≈ {value} USD',
    emailLabel: 'Barua Pepe',
    phoneLabel: 'Nambari ya Simu (WhatsApp / Kupiga)',
    phonePlaceholder: 'Mfano: +243 970 000 000',
    defaultAddressLabel: 'Anwani ya Uwasilishaji ya Kawaida (Lubumbashi)',
    defaultAddressPlaceholder: 'Manispaa, Mtaa, Nambari...',
    saveButton: 'Hifadhi',
    saving: 'Inahifadhi...',
    saveSuccess: 'Taarifa zimehifadhiwa kikamilifu.',

    // Address Form
    addressFormTitle: 'Anwani ya Uwasilishaji Lubumbashi',
    communeLabel: 'Manispaa (Commune)',
    communePlaceholder: 'Chagua manispaa yako',
    landmarkLabel: 'Eneo la Karibu Zaidi',
    landmarkPlaceholder: 'Chagua eneo',
    landmarkInputPlaceholder: 'Mfano: Kituo cha Horizon, Mzunguko wa Carrefour',
    streetLabel: 'Barabara, Nambari, Maelezo ya Nyumba',
    streetPlaceholder: 'Mfano: Avenue Kapenda N°42, Mlango wa chuma mweusi',
    mapsLinkLabel: 'Kiungo cha Google Maps (Hiari)',
    mapsLinkPlaceholder: 'Bandika kiungo cha kushiriki cha Google Maps...',

    // Order Tracking
    stepValidation: 'Uthibitishaji',
    stepPreparation: 'Maandalizi',
    stepDelivery: 'Inasafirishwa',
    stepDelivered: 'Imewasilishwa',
    orderCancelled: 'Agizo hili limeghairiwa.',

    // Orders Page
    ordersTitle: 'Historia ya Maagizo',
    ordersSubtitle: 'Fuatilia maendeleo ya ununuzi wako kwa wakati halisi.',
    ordersLoginPrompt: 'Ingia ili kuona historia na ufuatiliaji wa maagizo yako.',
    ordersEmpty: 'Hakuna maagizo kwa sasa',
    ordersEmptySubtitle: 'Bidhaa ulizozinunua zitaonekana hapa na ufuatiliaji.',
    ordersExplore: 'Tazama mikusanyiko',
    ordersLoading: 'Inapakia maagizo yako...',
    orderNumber: 'Agizo',
    orderTotal: 'Jumla',
    orderQuantity: 'Idadi',
    orderViewItem: 'Tazama bidhaa',
    orderCreatedIds: 'Nambari za maagizo yaliyoundwa:',

    // Checkout Page
    checkoutTitle: 'Uthibitishaji & Malipo ya Agizo',
    backToCart: 'Rudi kwenye kikapu',
    cashOnDeliveryDesc: 'Uwasilishaji nyumbani Lubumbashi',
    inStorePickupDesc: 'Kuchukua moja kwa moja kwa muuzaji (Bure)',
    loginToCheckout: 'Lazima uwe umeingia ili kukamilisha agizo lako.',
    loginToCheckoutLink: 'Bonyeza hapa kuingia',
    orderSummaryTitle: 'Jumla ya Agizo',
    processing: 'Inashughulikia...',
    secureTransaction: '🔒 Muamala salama uliohakikishwa na Zando Yetu.',
    addressRequired: 'Tafadhali jaza sehemu zote za anwani ya uwasilishaji zinazohitajika.',
    checkoutError: 'Kosa limetokea wakati wa malipo.',
    backToShop: 'Rudi dukani',

    // Cart Page
    clearCart: 'Futa kikapu',
    removeItem: 'Ondoa',
    orderSummary: 'Muhtasari wa Agizo',
    freeDeliveryThreshold: 'Bure (Kuanzia $50)',
    viewFullCart: 'Tazama Kikapu Kamili',

    // Cart Drawer Item Labels
    sizeLabel: 'Ukubwa',
    colorLabel: 'Rangi',

    // Promo Code
    promoCodeTitle: 'Msimbo wa Promo',
    promoCodeActive: 'Msimbo {code} (-{percent}%) unatumika',
    promoCodeInvalid: 'Msimbo wa promo batili au umekwisha.',
    promoCodeEmpty: 'Tafadhali ingiza msimbo.',
    promoCodeExample: 'Mfano: ZANDO10',

    // Fidelity Points
    fidelityTitle: 'Alama za Uaminifu',
    fidelityAvailable: 'Alama {count} zinapatikana',
    fidelityRate: 'Alama 1 = Punguzo la $0.20 USD moja kwa moja kwenye agizo lako.',
    fidelityDiscount: 'Punguzo lililotolewa: -{amount}',

    // Mobile Nav
    navHome: 'Nyumbani',
    navOrders: 'Maagizo',
    navCart: 'Kikapu',
    navProfile: 'Wasifu',

    // Footer
    footerDescription: 'Soko la kwanza la mitindo na wabunifu wa ndani huko Lubumbashi. Ungana na maduka bora ya eneo.',
    footerCommunesTitle: 'Maeneo ya Uwasilishaji',
    footerCommunesList1: 'Lubumbashi Centre & Golf',
    footerCommunesList2: 'Kampemba & Bel-Air',
    footerCommunesList3: 'Annexe & Joli Site',
    footerCommunesList4: 'Katuba & Kenya',
    footerCommunesList5: 'Kamalondo & Ruashi',
    footerCustomerServiceTitle: 'Huduma kwa Wateja',
    footerOrderTracking: 'Ufuatiliaji wa Agizo',
    footerMyCart: 'Kikapu Changu',
    footerMyAccount: 'Akaunti Yangu',
    footerLoginRegister: 'Ingia / Jisajili',
    footerPaymentTitle: 'Malipo & Sarafu',
    footerPaymentDesc: 'Tunakubali malipo ya Franki za Congo (CDF) na Dola za Kimarekani (USD) wakati wa kupokea au dukani.',
    footerCopyright: '© {year} Zando Yetu. Haki zote zimehifadhiwa. Lubumbashi, Jamhuri ya Kidemokrasia ya Congo.',
    footerGuaranteeDeliveryDesc: 'Lubumbashi, Haut-Katanga (DRC)',
    footerGuaranteePaymentDesc: 'Pesa wakati wa kupokea & Pesa za Simu',
    footerGuaranteeReturnsDesc: 'Uthibitishaji papo hapo wakati wa kupokea',

    // Login / Connection
    loginButton: 'Ingia',
    loginRegisterMobile: 'Ingia / Jisajili',

    // WhatsApp Inquiries
    whatsappInquiry: 'Ongea kupitia WhatsApp',
    whatsappStoreInquiry: 'Wasiliana na duka kupitia WhatsApp',
    whatsappProductMsg: 'Habari, ninavutiwa na bidhaa "{title}" ({price}) kwenye Zando Yetu: {link}',
    whatsappStoreMsg: 'Habari, ninawasiliana nawe kutoka duka lako {name} kwenye Zando Yetu.',

    // Product & Variants
    scarcityWarning: '🔥 Zimebaki {count} tu!',
    selectSize: 'Ukubwa uliochaguliwa',
    selectColor: 'Rangi iliyochaguliwa',
    viewCatalog: 'Rudi kwenye orodha',
    productNotFound: 'Bidhaa haipatikani',
    productNotFoundDesc: 'Bidhaa hii haipatikani tena au imeondolewa.',
    storeNotFound: 'Duka halipatikani',
    storeNotFoundDesc: 'Duka hili halifanyi kazi tena kwenye Zando Yetu.',
    itemsForSale: 'Bidhaa zinazouzwa ({count})',
    noItemsInStore: 'Hakuna bidhaa kwenye hisa kwa sasa',
    noItemsInStoreDesc: 'Rudi hivi karibuni kuona bidhaa mpya.',
    stockRemaining: 'Zimebaki {count}',
    colorAvailable: '{color}',

    // Reviews
    reviewTitle: 'Maoni na Tathmini za Wateja',
    leaveReview: 'Andika maoni kuhusu bidhaa hii',
    reviewPlaceholder: 'Toa maoni yako kuhusu ubora, ukubwa au uwasilishaji...',
    submitReview: 'Tuma Maoni',
    submittingReview: 'Inatuma...',
    noReviews: 'Hakuna maoni kwa sasa. Kuwa wa kwanza kutoa maoni!',
    mustLoginToReview: 'Ingia ili kuacha maoni kuhusu bidhaa hii.',
    verifiedCustomer: 'Ununuzi Uliothibitishwa',
    wishlistAdded: 'Imeongezwa kwenye vipendwa',
    wishlistRemoved: 'Imeondolewa kwenye vipendwa',

    // Mega Menu & Storefront V2
    allRayons: 'Mikusanyiko Yote',
    megaMenuWomen: 'Wanawake',
    megaMenuMen: 'Wanaume',
    megaMenuKids: 'Watoto',
    megaMenuDresses: 'Magauni na Suti',
    megaMenuShoes: 'Viatu',
    megaMenuBags: 'Mikoba na Vifaa',
    megaMenuDesigners: 'Wabunifu wa Katanga',
    dealsTitle: 'Ofa Zetu Bora',
    dealsSubtitle: 'Mkusanyiko maalum wa bei nafuu kwa Lubumbashi',
    trendsTitle: 'Zinazopendwa Zaidi',
    officialStoresTitle: 'Maduka Rasmi',
    expressDeliveryTag: 'Uwasilishaji wa Saa 24-48 Lubumbashi',
    newArrivals: 'Bidhaa Mpya',
    bestSellers: 'Zinazouzika Zaidi',
    under20: 'Chini ya $20',
    guestBannerText: 'Jiunge na Zando Yetu ili upate alama za uaminifu na ufuatilie maagizo yako!',
    guestBannerBtn: 'Fungua Akaunti',
    wishlistTitle: 'Vipendwa Vyangu',
    featuredBrandHighlight: 'Mkusanyiko Maalum wa Lubumbashi',
    flashSaleEndsSoon: 'Ofa ya muda mfupi',
    viewAllDeals: 'Tazama ofa zote',
  },
};

interface LanguageState {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: keyof typeof translations['fr'], variables?: Record<string, string | number>) => string;
}

export const useLanguageStore = create<LanguageState>()(
  persist(
    (set, get) => ({
      language: 'fr',
      setLanguage: (language) => set({ language }),
      t: (key, variables) => {
        const lang = get().language;
        const dict = translations[lang] || translations.fr;
        let str = dict[key] || translations.fr[key] || key;
        if (variables) {
          Object.entries(variables).forEach(([k, v]) => {
            str = str.replace(new RegExp(`\\{${k}\\}`, 'g'), String(v));
          });
        }
        return str;
      },
    }),
    {
      name: 'zando-language-storage',
    }
  )
);
